In [1]:
import numpy

array([], dtype=float64)

In [6]:
a = numpy.array([])
a.size == 0

True

In [15]:
def test():
    print("2635263r")
    for i in range(10):
        yield i**2

# for i in range(20):
#     print(next(test()))
gen = test()

In [20]:
while True:
    try:
        print(next(gen))
    except:
        break

9
16
25
36
49
64
81


In [22]:
import numpy as np
np.random.randn(2,3)

array([[-0.98352497, -0.74758802,  1.4732546 ],
       [-0.79125377, -1.20842845, -0.79839399]])

In [27]:
%%time
for i in range(10000):
    a = []
    for j in range(10000):
        a.append([7])

CPU times: total: 45.5 s
Wall time: 45.5 s


In [45]:
vec = [np.random.randn(32) for i in range(100)]


In [74]:
np.zeros((3,32))[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
a = np.random.randn(2,3)
a.size, a.shape, len(a)

(6, (2, 3), 2)

In [73]:
np.stack([np.zeros(32), np.ones(32)], axis=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [1]:
from sklearn.feature_extraction import FeatureHasher

In [11]:
h = FeatureHasher(n_features=3)
D = [{'dog': 1, 'cat':10, 'elephant':4}]
f = h.transform(D)
f.toarray()

array([[-1., 10., -4.]])

In [13]:
f.toarray() / f.toarray().sum()

array([[-0.2,  2. , -0.8]])

In [3]:
import numpy as np
set(np.array(["1","2","3"]))

{'1', '2', '3'}

In [6]:
import pathlib
import os
pathlib.Path("D:/data/CFG/public.tar").parent

WindowsPath('D:/data/CFG')

In [7]:
os.path.join(pathlib.Path("D:/data/CFG/public.tar").parent, "result.csv")

'D:\\data\\CFG\\result.csv'

In [20]:
hash("arm32gcco0") % 130

79

In [17]:
129 % 130

129